Repository BE14-NoB/pick-frontend, pull requests merged in 2025-04, with the labels that each got.

#5 [Feature] 푸터 / 푸터 컴포넌트 제작
  package-lock.json
  pick-front/src/App.vue
  pick-front/src/components/MyFooter.vue
Labels: enhancement

#11 [Feat] post / 배정된 공통 컴포넌트 완성 + 게시판 사이드바 구현
  pick-front/index.html
  pick-front/src/assets/post/icons8-search.svg
  pick-front/src/components/post/ComboBox.vue
  pick-front/src/components/post/PostList.vue
  pick-front/src/components/post/SearchBox.vue
  pick-front/src/components/post/SearchComboBox.vue
  pick-front/src/components/post/SideBar.vue
  pick-front/src/components/post/Write.vue
  pick-front/src/router/router.js
  pick-front/src/views/PostView.vue
Labels: enhancement

#14 [Feature] 조회 목록 및 페이지네이션, 멤버 공통 사이드바 컴포넌트 생성
  pick-front/src/assets/issueMaker.png
  pick-front/src/assets/matchingImg.png
  pick-front/src/components/List.vue
  pick-front/src/components/MemberSideBar.vue
  pick-front/src/components/Pagination.vue
  pick-front/src/main.js
  pick-front/src/router/router.js
Labels: enhancement

#15 feat : 프로필 이미지 클릭 및 회원정보,프로필 구조 생성
  pick-front/src/components/MyHeader.vue
  pick-front/src/components/member/MemberInfo.vue
  pick-front/src/components/member/MemberProfile.vue
  pick-front/src/router/router.js
  pick-front/src/views/MemberView.vue
Labels: enhancement

#16 Feature/sh/projects/project view2
  pick-front/package-lock.json
  pick-front/package.json
  pick-front/src/project/components/ProjectLayout.vue
  pick-front/src/project/components/Sidebar.vue
  pick-front/src/project/data/menuData.js
  pick-front/src/project/views/CommitListView.vue
  pick-front/src/project/views/CreateIssueView.vue
  pick-front/src/project/views/CreatePRView.vue
  pick-front/src/project/views/IssueListView.vue
  pick-front/src/project/views/PRListView.vue
  pick-front/src/project/views/ProjectView.vue
  pick-front/src/router/router.js
Labels: bug, enhancement

#19 refactor: 회원 정보 페이지 수정
  pick-front/index.html
  pick-front/src/components/member/MemberInfo.vue
Labels: enhancement

#20 [Feature] 프로젝트 탭스 구현
  pick-front/src/components/project/ProjectTabs.vue
  pick-front/src/project/components/ProjectLayout.vue
  pick-front/src/project/components/ProjectSidebar.vue
  pick-front/src/project/components/ProjectTabs.vue
  pick-front/src/views/project/pr/CreatePRView.vue
Labels: enhancement

#25 [Feature] 헤더 및 메칭 조회바 구현
  pick-front/src/components/MyHeader.vue
  pick-front/src/components/matching/MatchingResult.vue
  pick-front/src/components/matching/MatchingSearch.vue
  pick-front/src/main/views/MainView.vue
  pick-front/src/router/router.js
  pick-front/src/views/MatchView.vue
Labels: :sparkles: enhancement

#28 [Feat] 검색창 고도화
  pick-front/src/components/MyFooter.vue
  pick-front/src/components/MyHeader.vue
  pick-front/src/components/post/PostList.vue
  pick-front/src/components/post/SearchBox.vue
  pick-front/src/components/post/SideBar.vue
  pick-front/src/components/post/SinglePost.vue
  pick-front/src/router/router.js
  pick-front/src/views/PostView.vue
Labels: :sparkles: enhancement

#30 [Design] proeject / 프로젝트 공용 페이지 디자인 수정
  pick-front/src/components/project/ProjectLayout.vue
  pick-front/src/components/project/ProjectSidebar.vue
  pick-front/src/components/project/ProjectTabs.vue
Labels: 🎨 design

#34 feat: 회원 프로필 추가
  pick-front/src/components/member/MemberInfo.vue
  pick-front/src/components/member/MemberProfile.vue
Labels: :sparkles: enhancement

#38 [프로젝트] 경로 수정
  pick-front/src/App.vue
  pick-front/src/common/MyFooter.vue
  pick-front/src/common/MyHeader.vue
  pick-front/src/common/ProjectCard.vue
  pick-front/src/components/project/CategoryChip.vue
  pick-front/src/components/project/LinkChip.vue
  pick-front/src/components/project/ProjectLayout.vue
  pick-front/src/components/project/ProjectReviewCard.vue
  pick-front/src/components/project/ThumbNailMockup.vue
  pick-front/src/data/project/MenuData.js
  pick-front/src/project/views/ProjectDetailView.vue
  pick-front/src/project/views/ProjectListView.vue
  pick-front/src/router/router.js
  pick-front/src/views/project/commit/CommitListView.vue
  pick-front/src/views/project/dashboard/DashboardView.vue
Labels: 🔧 refactoring

#40 design: 프로젝트 사이드바 길이 수정
  pick-front/src/components/project/ProjectSidebar.vue
Labels: 🎨 design

#46 [feature] 회원 로그인 기능 추가
  pick-front/src/components/common/MyHeader.vue
  pick-front/src/components/member/MemberSignUp.vue
  pick-front/src/router/router.js
Labels: :sparkles: enhancement

#48 Feature: 로그인 모달 추가
  pick-front/src/components/common/MyHeader.vue
  pick-front/src/components/member/MemberLogin.vue
  pick-front/src/components/member/MemberSignUp.vue
  pick-front/src/router/router.js
Labels: :sparkles: enhancement

#50 feat: 로그아웃 추가
  pick-front/src/components/common/MyHeader.vue
Labels: :sparkles: enhancement

#52 feat : 회원가입 모달 추가
  pick-front/src/components/common/MyHeader.vue
  pick-front/src/components/member/MemberSignUp.vue
  pick-front/src/router/router.js
Labels: :sparkles: enhancement

#54 [Refactor] 프로젝트 관련 파일 폴더구조 변경
  pick-front/src/components/git/views/IssueList.vue
  pick-front/src/components/project/IssueCreateButton.vue
  pick-front/src/data/project/MenuData.js
  pick-front/src/project/views/IssueListView.vue
  pick-front/src/router/router.js
  pick-front/src/views/project/ProjectDetailView.vue
  pick-front/src/views/project/ProjectInfoView.vue
  pick-front/src/views/project/ProjectListView.vue
  pick-front/src/views/project/ProjectView.vue
  pick-front/src/views/project/issue/IssueList.vue
Labels: 🔧 refactoring

#56 [Refactor] 이슈 목록 조회 페이지 개선
  pick-front/src/components/Pagination.vue
  pick-front/src/json/project_issuelist.json
  pick-front/src/views/project/issue/IssueList.vue
Labels: 🔧 refactoring

#58 feat : 유효성 검사 및 기본 폼 작성
  pick-front/src/components/member/MemberSignUp.vue
Labels: :sparkles: enhancement

#60 [Feature] PR 조회 페이지 생성
  pick-front/src/json/project_prlist.json
  pick-front/src/views/project/pr/PRListView.vue
Labels: :sparkles: enhancement

#61 [Feature] project / 이슈, PR 생성하기 페이지 완
  pick-front/package-lock.json
  pick-front/package.json
  pick-front/src/components/project/FormEditor.vue
  pick-front/src/components/project/ProjectDropdown.vue
  pick-front/src/components/project/pr/PRBranchSelector.vue
  pick-front/src/components/project/pr/PRCommitList.vue
  pick-front/src/components/project/pr/PRFileChanges.vue
  pick-front/src/components/project/pr/PRFormSection.vue
  pick-front/src/data/project/MenuData.js
  pick-front/src/router/router.js
  pick-front/src/views/project/issue/CreateIssueView.vue
  pick-front/src/views/project/pr/CreatePRView.vue
  pick-front/src/views/project/pr/ReviewPRView.vue
Labels: :sparkles: enhancement

#63 [Refactor] PR 조회 페이지에 PR 생성하기 버튼 추가
  pick-front/src/components/project/PRCreateButton.vue
  pick-front/src/views/project/pr/PRListView.vue
Labels: 🔧 refactoring

#65 [Feature] 커밋 내역 조회 페이지 생성
  pick-front/src/json/project_commitlist.json
  pick-front/src/views/project/commit/CommitListView.vue
  pick-front/src/views/project/pr/PRListView.vue
Labels: :sparkles: enhancement

#71 refactor: 드롭다운 수정및 회원가입 수정
  pick-front/package.json
  pick-front/src/components/common/MyHeader.vue
  pick-front/src/components/member/MemberSignUp.vue
Labels: 🔧 refactoring

#72 [Refactor] 일일미션 페이지 수정
  pick-front/src/components/MemberSideBar.vue
  pick-front/src/components/dailymission/components/ProgressBar.vue
  pick-front/src/components/dailymission/components/TodayDate.vue
  pick-front/src/components/dailymission/views/DailyMission.vue
  pick-front/src/json/dailymission.json
Labels: 🔧 refactoring

#74 [Refactor] 멤버 사이드바 수정
  pick-front/src/components/MemberSideBar.vue
Labels: 🔧 refactoring

#76 [Feature] 프로젝트 회의록, 팀원, 프로젝트 후기 기능 구현
  pick-front/src/components/List.vue
  pick-front/src/components/common/Pagination.vue
  pick-front/src/components/project/MeetingCreateButton.vue
  pick-front/src/components/project/MeetingSaveButton.vue
  pick-front/src/components/project/MeetingWidget.vue
  pick-front/src/components/project/MemberWidget.vue
  pick-front/src/components/project/ProjectLayout.vue
  pick-front/src/components/project/ThumbnailUploader.vue
  pick-front/src/components/project/dashboard/GitWidgetCard.vue
  pick-front/src/components/project/member/MemberReviewModal.vue
  pick-front/src/components/project/review/ProjectReviewModal.vue
  pick-front/src/data/project/MenuData.js
  pick-front/src/json/project_meeting.json
  pick-front/src/json/project_meeting_db.json
  pick-front/src/json/project_meeting_list.json
  pick-front/src/router/router.js
  pick-front/src/views/project/commit/CommitListView.vue
  pick-front/src/views/project/dashboard/DashboardView.vue
  pick-front/src/views/project/info/ProjectInfoUpdate.vue
  pick-front/src/views/project/info/ProjectInfoView.vue
  pick-front/src/views/project/issue/IssueList.vue
  pick-front/src/views/project/meeting/CreaetMeeting.vue
  pick-front/src/views/project/meeting/MeetingDetail.vue
  pick-front/src/views/project/meeting/MeetingList.vue
  pick-front/src/views/project/member/ProjectMemberView.vue
  pick-front/src/views/project/pr/PRListView.vue
  pick-front/src/views/project/review/ProjectReview.vue
Labels: :sparkles: enhancement

#79 [Feat] post / 카테고리 별 게시글 목록 조회 기능 추가
  pick-front/src/components/common/ComboBox.vue
  pick-front/src/components/common/SearchComboBox.vue
  pick-front/src/components/post/List.vue
  pick-front/src/components/post/PostList.vue
  pick-front/src/components/post/SideBar.vue
  pick-front/src/components/post/SinglePost.vue
  pick-front/src/components/post/Write.vue
  pick-front/src/json/post_list.json
  pick-front/src/router/router.js
  pick-front/src/views/PostView.vue
Labels: :sparkles: enhancement

#84 feature : 회원 기능 추가
  pick-front/package-lock.json
  pick-front/package.json
  pick-front/src/components/common/MyHeader.vue
  pick-front/src/components/member/MemberInfo.vue
  pick-front/src/components/member/MemberLogin.vue
  pick-front/src/components/member/MemberSignUp.vue
  pick-front/src/json/users.json
  pick-front/src/main.js
  pick-front/src/router/router.js
  pick-front/src/stores/auth.js
  pick-front/src/utils/jsonStorage.js
  pick-front/src/views/member/MemberEditView.vue
  pick-front/vite.config.js
Labels: :sparkles: enhancement

#88 [Hotfix] post / 페이지네이션 경로 변경 반영
  pick-front/src/components/post/PostList.vue
  pick-front/src/components/post/SinglePost.vue
Labels: 🚨 HOTFIX

#87 [Feature] 매칭 페이지, 매칭 결과 조회 페이지 구현
  pick-front/src/components/MyHeader.vue
  pick-front/src/components/matching/MatchingResult.vue
  pick-front/src/components/matching/MatchingSearch.vue
  pick-front/src/components/matching/MatchingSideBar.vue
  pick-front/src/components/matching/TeamMemberCard.vue
  pick-front/src/router/router.js
  pick-front/src/views/MatchView.vue
  pick-front/src/views/Matching/MatchView.vue
  pick-front/src/views/Matching/SearchResult.vue
Labels: :sparkles: enhancement, 🔧 refactoring

#91 [Refactor] PR 생성 버튼 클릭 시 이동 경로 변경
  pick-front/src/components/project/PRCreateButton.vue
Labels: 🔧 refactoring

#93 [Feature] 매칭 생성 모달창
  pick-front/src/components/matching/MatchingCreate.vue
  pick-front/src/components/matching/MatchingSearch.vue
  pick-front/src/components/matching/MatchingSideBar.vue
Labels: :sparkles: enhancement

#96 [refactor] 회원 프로필 사진 수정
  pick-front/src/components/member/MemberProfile.vue
Labels: 🔧 refactoring

#98 [Refactor] project / PR 생성하기 페이지
  pick-front/src/components/project/ProjectSidebar.vue
  pick-front/src/components/project/pr/PRBranchSelector.vue
  pick-front/src/data/project/MenuData.js
  pick-front/src/views/project/pr/CreatePRView.vue
  pick-front/src/views/project/pr/ReviewPRView.vue
Labels: 🔧 refactoring

#100 refactor : 라우팅 수정
  pick-front/src/components/MemberSideBar.vue
  pick-front/src/components/common/MyHeader.vue
Labels: :sparkles: enhancement

#101 [Design] PR 리뷰 페이지 수정
  pick-front/src/components/project/pr/PRCommitList.vue
Labels: 🎨 design

#105 refactor : 헤더 프로필 사진 변경
  pick-front/src/assets/member/avatar.png
  pick-front/src/components/common/MyHeader.vue
  pick-front/src/components/member/MemberInfo.vue
  pick-front/src/components/member/MemberProfile.vue
  pick-front/src/components/member/MemberSignUp.vue
Labels: 🔧 refactoring

#109 refactor : 사진 통일
  pick-front/src/assets/member/profile-image-1.png
  pick-front/src/assets/member/profile-image-2.png
  pick-front/src/assets/member/profile-image-3.png
  pick-front/src/assets/member/profile-image-4.png
  pick-front/src/assets/member/profile-image-5.png
  pick-front/src/assets/member/profile-image-6.png
  pick-front/src/assets/member/project-1.png
  pick-front/src/assets/member/project-11.png
  pick-front/src/assets/member/project-3.png
  pick-front/src/components/common/MyHeader.vue
  pick-front/src/components/member/MemberInfo.vue
  pick-front/src/components/member/MemberProfile.vue
Labels: 🔧 refactoring

#111 [Refactor] 이슈 목록 조회 페이지 수정
  pick-front/src/assets/img/member_profile/cm.png
  pick-front/src/assets/img/member_profile/hm.png
  pick-front/src/assets/img/member_profile/ms.png
  pick-front/src/assets/img/member_profile/sh.png
  pick-front/src/assets/img/member_profile/sw.png
  pick-front/src/assets/img/member_profile/sy.png
  pick-front/src/components/List.vue
  pick-front/src/json/project_issuelist.json
  pick-front/src/views/project/issue/IssueList.vue
Labels: 🔧 refactoring

#113 refactor : 모달 관련 수정 완료
  pick-front/src/components/common/MyHeader.vue
  pick-front/src/components/member/MemberSignUp.vue
Labels: :sparkles: enhancement

#115 [Refactor] 커밋 목록 조회 페이지 수정
  pick-front/src/json/project_commitlist.json
  pick-front/src/views/project/commit/CommitListView.vue
Labels: 🔧 refactoring

#117 [Feat] post / 게시글 상단의 댓글 수 동기화
  pick-front/src/components/post/CommentList.vue
  pick-front/src/components/post/PostList.vue
  pick-front/src/components/post/SinglePost.vue
  pick-front/src/json/post_list.json
  pick-front/src/json/post_member.json
Labels: :sparkles: enhancement

#120 feat: 푸터 라우팅 연결
  pick-front/src/components/common/MyFooter.vue
Labels: :sparkles: enhancement

#122 [Refactor] pr 목록 조회 페이지 수정
  pick-front/src/json/project_prlist.json
  pick-front/src/views/project/pr/PRListView.vue
Labels: 🔧 refactoring

#125 [Refactor] 이슈 조회 페이지 및 닉네임 수정
  pick-front/src/json/project_commitlist.json
  pick-front/src/json/project_issuelist.json
  pick-front/src/json/project_prlist.json
  pick-front/src/views/project/issue/IssueList.vue
Labels: 🔧 refactoring

#126 [Refactor] 매칭 생성 css 수정
  pick-front/src/components/matching/MatchingCreate.vue
  pick-front/src/components/matching/MatchingSearch.vue
  pick-front/src/components/matching/MatchingSideBar.vue
  pick-front/src/main/views/MainView.vue
Labels: :sparkles: enhancement, 🔧 refactoring

#127 [Refactor] 프로필 사진 적용
  pick-front/src/components/project/MemberWidget.vue
  pick-front/src/json/participants.json
  pick-front/src/views/project/finished/ProjectDetailView.vue
  pick-front/src/views/project/meeting/CreateMeeting.vue
  pick-front/src/views/project/meeting/MeetingDetail.vue
  pick-front/src/views/project/meeting/MeetingList.vue
  pick-front/src/views/project/member/ProjectMemberView.vue
  pick-front/src/views/project/review/ProjectReview.vue
Labels: 🔧 refactoring

#131 refactor: 회원 후기 닉네임 정정
  pick-front/src/json/reviews.json
Labels: 🔧 refactoring

#132 Refactor: 더미데이터 json으로 분리
  pick-front/src/components/matching/MatchingCreate.vue
  pick-front/src/components/matching/MatchingResult.vue
  pick-front/src/components/matching/MatchingSearch.vue
  pick-front/src/components/matching/MatchingSideBar.vue
  pick-front/src/json/matching_filter.json
  pick-front/src/json/matching_list.json
Labels: :sparkles: enhancement, 🔧 refactoring

#133 [Doc] 더미데이터 수정
  pick-front/src/json/matching_list.json
Labels: :page_facing_up: documentation

#136 [Feature] git / 프론트 페이지 pr 생성 기능 연동
  pick-front/src/components/project/pr/PRBranchSelector.vue
  pick-front/src/components/project/pr/PRCommitList.vue
  pick-front/src/components/project/pr/PRFileChanges.vue
  pick-front/src/components/project/pr/PRFormSection.vue
  pick-front/src/views/project/pr/CreatePRView.vue
  pick-front/src/views/project/pr/ReviewPRView.vue
Labels: 🎨 design, :sparkles: enhancement

#137 [Refactor] 매칭 리스트 더미데이터 json서버연결
  pick-front/src/components/matching/MatchingResult.vue
Labels: :sparkles: enhancement, 🔧 refactoring

#138 [Refactor] 매칭 로딩 로직 오타 수정
  pick-front/src/components/matching/MatchingResult.vue
Labels: 🎨 design

#140 [Feat] post / 대댓글 표시되도록 구현
  pick-front/src/components/post/CommentItem.vue
  pick-front/src/components/post/CommentList2.vue
  pick-front/src/components/post/SinglePost.vue
Labels: :sparkles: enhancement

#141 [Design] post / 검색창과 글쓰기 버튼 정렬
  pick-front/src/components/post/PostList.vue
  pick-front/src/components/post/SinglePost.vue
Labels: 🎨 design

#146 [Feature] 회의록 삭제 기능 구현
  pick-front/src/components/member/MemberLogin.vue
  pick-front/src/components/project/MeetingSaveButton.vue
  pick-front/src/json/project_meeting_db.json
  pick-front/src/json/send_member_review.json
  pick-front/src/views/project/meeting/CreateMeeting.vue
  pick-front/src/views/project/meeting/MeetingDetail.vue
  pick-front/src/views/project/meeting/MeetingList.vue
  pick-front/src/views/project/member/ProjectMemberView.vue
Labels: :sparkles: enhancement, 🔧 refactoring

#149 [Refactor] 멤버뷰 구조 변경 및 매칭 관련 페이지 추가
  pick-front/src/components/MemberSideBar.vue
  pick-front/src/components/dailymission/views/DailyMission.vue
  pick-front/src/components/matching/DecisionModal.vue
  pick-front/src/components/matching/MatchingCreate.vue
  pick-front/src/components/matching/MatchingResult.vue
  pick-front/src/components/matching/MatchingSearch.vue
  pick-front/src/components/matching/PendingMatching.vue
  pick-front/src/components/matching/RecruitingMatching.vue
  pick-front/src/components/member/MemberInfo.vue
  pick-front/src/json/pending_list.json
  pick-front/src/json/recruiting_list.json
  pick-front/src/router/router.js
  pick-front/src/views/MemberView.vue
Labels: :sparkles: enhancement, 🔧 refactoring

#150 [Feat] git / 이슈 리스트 깃 API 연동
  pick-front/src/views/project/issue/IssueList.vue
Labels: :sparkles: enhancement

#152 [Refactor] 멤버 사이드바 css 적용되게 수정
  pick-front/src/components/MemberSideBar.vue
  pick-front/src/components/matching/CompletedProject.vue
  pick-front/src/router/router.js
Labels: 🔧 refactoring

#156 [Refactor] PICK 파비콘 및 서비스명 수정
  pick-front/index.html
  pick-front/public/pick_icon.png
  pick-front/public/pick_logo.png
  pick-front/src/json/project_entry.json
  pick-front/src/views/project/dashboard/DashboardView.vue
  pick-front/src/views/project/finished/ProjectDetailView.vue
  pick-front/src/views/project/finished/ProjectListView.vue
  pick-front/src/views/project/info/ProjectInfoView.vue
  pick-front/src/views/project/meeting/CreateMeeting.vue
  pick-front/src/views/project/meeting/MeetingDetail.vue
  pick-front/src/views/project/member/ProjectMemberView.vue
Labels: 🎨 design
